### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by storeman** [WillsherSystems/ansible-users#3]
Thanks for your repo. On Galaxy the link to Github is broken:
https://galaxy.ansible.com/list#/roles/710

Anyway, there is a typo in either the defaults/main.yml or tasks/ssh_keys.yml. The latter expects `users_ssh_keys` while the first defines `user_ssh_keys`

**Comment by mattwillsher** [comment]
Hi @storeman 

That role page somewhat deprecated for https://galaxy.ansible.com/list#/roles/2562. I'll remove that one.

I'll fix the typo.

**Comment by mattwillsher** [comment]
0.2.3 has been released with this fix in. Thanks for the report!
