### ISSUE TITLE
Error when user already exists

### ISSUE THREAD

**Issue by shadjifotis** [WillsherSystems/ansible-users#4]
TASK: [ansible-users-master | Load OS specific values] ************************
ok: [miluvlxxx] => (item=/var/cm/local/ansible/roles/ansible-users-master/vars/RedHat.yml)

TASK: [ansible-users-master | Create groups] **********************************
ok: [miluvlxxx] => (item={'gid': 10001, 'name': 'ccdev'})
ok: [miluvlxxx] => (item={'gid': 10099, 'name': 'ccadmg'})
ok: [miluvlxxx] => (item={'gid': 532, 'name': 'mcinstall'})
ok: [miluvlxxx] => (item={'gid': 576, 'name': 'mcadmin'})

TASK: [ansible-users-master | Create per-user groups] *************************
failed: [miluvlxxx] => (item={'comment': 'Some User', 'is_admin': False, 'name': 'shadjifo', 'groups': ['ccdev,ccadmg,mcinstall,mcadmin'], 'uid': 10001}) => {"failed": true, "item": {"comment": "Some User", "groups": ["ccdev,ccadmg,mcinstall,mcadmin"], "is_admin": false, "name": "shadjifo", "uid": 10001}, "name": "shadjifo"}
msg: groupadd: GID '10001' already exists

FATAL: all hosts have already failed -- aborting

**Comment by mattwillsher** [comment]
Hi @shadjifotis 

You'll need to override the gid for the group shadjifo in the data you pass via users_groups and setting the users groups in the users dict and/or disable per user groups by setting users_per_user_groups to false.

**Comment by shadjifotis** [comment]
I set users_per_user_groups to false now get different error
failed: [miluvlxxxx] => (item={'comment': 'Sebastien Hadjifotis', 'is_admin': False, 'name': 'shadjifo', 'groups': ['ccdev,ccadmg,mcinstall,mcadmin'], 'uid': 10001}) => {"failed": true, "item": {"comment": "Sebastien Hadjifotis", "groups": ["ccdev,ccadmg,mcinstall,mcadmin"], "is_admin": false, "name": "shadjifo", "uid": 10001}}
msg: Group shadjifo does not exist

**Comment by mattwillsher** [comment]
Do you have another group of gid 10001? Have you set a group for the shadjifo user?

**Comment by shadjifotis** [comment]
yes ccdev is gid 10001.

ok: [miluvlxxx] => (item={'gid': 10001, 'name': 'ccdev'})
ok: [miluvlxxx] => (item={'gid': 10099, 'name': 'ccadmg'})
ok: [miluvlxxx] => (item={'gid': 532, 'name': 'mcinstall'})
ok: [miluvlxxx] => (item={'gid': 576, 'name': 'mcadmin'})

I don't want to have a group shadjifo. Is that required?
I have other users which works fine, they are in the ccdev, ccadmg, mcinstall and mcadmin groups.
They don't have groups that are named the same as the username.

**Comment by shadjifotis** [comment]
I believe I have fixed the issue, i set item group for shadjifo to ccdev and that fixed the issue.

**Comment by mattwillsher** [comment]
Glad you got it working!
